version: '3.8'

services:
  app:
    image: aarenow95/lionmq:latest  # 使用 lionmq 的映像
    ports:
      - "80:80"
    environment:

      - PORT=80
      - SERVER_HOST=http://52.62.184.240
      - WATCHER_SERVER=ws://13.237.98.165
      - MONGODB_SERVER=mongodb+srv://Aaren:3030416@cluster0.mollxex.mongodb.net/?retryWrites=true&w=majority&tls=true&tlsAllowInvalidCertificates=true
      - MONGODB_DOCUMENT=LionMQ_node1
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: